"""empty message

Revision ID: 4fec710098c1
Revises: 8b6c62d6ef48
Create Date: 2024-07-01 19:15:24.517287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fec710098c1'
down_revision = '8b6c62d6ef48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('libro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('available_quantity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metodo_pago',
    sa.Column('id_metodo_pago', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_metodo_pago')
    )
    op.create_table('tipo_movimiento',
    sa.Column('id_tipo_movimiento', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_tipo_movimiento')
    )
    op.create_table('movimiento',
    sa.Column('id_movimiento', sa.Integer(), nullable=False),
    sa.Column('id_tipo_movimiento', sa.Integer(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_tipo_movimiento'], ['tipo_movimiento.id_tipo_movimiento'], ),
    sa.PrimaryKeyConstraint('id_movimiento')
    )
    op.create_table('detalles_movimiento',
    sa.Column('id_detalle_movimiento', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_movimiento', sa.Integer(), nullable=True),
    sa.Column('id_libro', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_libro'], ['libro.id'], ),
    sa.ForeignKeyConstraint(['id_movimiento'], ['movimiento.id_movimiento'], ),
    sa.PrimaryKeyConstraint('id_detalle_movimiento')
    )
    op.create_table('venta',
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('fecha_venta', sa.DateTime(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id_venta')
    )
    op.create_table('detalles_venta',
    sa.Column('id_detalle_venta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_venta', sa.Integer(), nullable=True),
    sa.Column('id_libro', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_venta', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_libro'], ['libro.id'], ),
    sa.ForeignKeyConstraint(['id_venta'], ['venta.id_venta'], ),
    sa.PrimaryKeyConstraint('id_detalle_venta')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalles_venta')
    op.drop_table('venta')
    op.drop_table('detalles_movimiento')
    op.drop_table('movimiento')
    op.drop_table('tipo_movimiento')
    op.drop_table('metodo_pago')
    op.drop_table('libro')
    # ### end Alembic commands ###
