"""empty message

Revision ID: 8b6c62d6ef48
Revises: 811d66407cb2
Create Date: 2024-07-01 19:10:36.892240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b6c62d6ef48'
down_revision = '811d66407cb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimiento')
    op.drop_table('libro')
    op.drop_table('metodo_pago')
    op.drop_table('tipo_movimiento')
    op.drop_table('detalles_movimiento')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detalles_movimiento',
    sa.Column('id_detalle_movimiento', sa.INTEGER(), nullable=False),
    sa.Column('id_movimiento', sa.INTEGER(), nullable=True),
    sa.Column('id_libro', sa.INTEGER(), nullable=True),
    sa.Column('cantidad', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['id_libro'], ['libro.id'], ),
    sa.ForeignKeyConstraint(['id_movimiento'], ['movimiento.id_movimiento'], ),
    sa.PrimaryKeyConstraint('id_detalle_movimiento')
    )
    op.create_table('tipo_movimiento',
    sa.Column('id_tipo_movimiento', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(), nullable=False),
    sa.Column('descripcion', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id_tipo_movimiento')
    )
    op.create_table('metodo_pago',
    sa.Column('id_metodo_pago', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), nullable=False),
    sa.Column('descripcion', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id_metodo_pago')
    )
    op.create_table('libro',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=100), nullable=False),
    sa.Column('precio', sa.FLOAT(), nullable=False),
    sa.Column('available_quantity', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimiento',
    sa.Column('id_movimiento', sa.INTEGER(), nullable=False),
    sa.Column('id_tipo_movimiento', sa.INTEGER(), nullable=True),
    sa.Column('fecha_hora', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['id_tipo_movimiento'], ['tipo_movimiento.id_tipo_movimiento'], ),
    sa.PrimaryKeyConstraint('id_movimiento')
    )
    # ### end Alembic commands ###
