"""empty message

Revision ID: cb5d3f369cf8
Revises: 4fec710098c1
Create Date: 2024-07-01 21:15:30.713612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb5d3f369cf8'
down_revision = '4fec710098c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apartado',
    sa.Column('id_apartado', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('fecha_limite', sa.DateTime(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('nombre_acreedor', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id_apartado')
    )
    op.create_table('detalles_apartado',
    sa.Column('id_detalle_apartado', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_apartado', sa.Integer(), nullable=True),
    sa.Column('id_libro', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_apartado', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_apartado'], ['apartado.id_apartado'], ),
    sa.ForeignKeyConstraint(['id_libro'], ['libro.id'], ),
    sa.PrimaryKeyConstraint('id_detalle_apartado')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalles_apartado')
    op.drop_table('apartado')
    # ### end Alembic commands ###
