# Generated by Django 5.0.4 on 2024-05-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('ID', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('Cantidad', models.DecimalField(decimal_places=0, max_digits=5)),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Titulo', models.CharField(max_length=100)),
                ('Autor', models.CharField(max_length=100)),
                ('Editorial', models.CharField(max_length=100)),
            ],
        ),
    ]
