# Generated by Django 5.0.4 on 2024-05-13 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metodo_pago',
            fields=[
                ('id_metodo_pago', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=0, max_digits=5)),
                ('fecha_venta', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='ID',
            new_name='id_libro',
        ),
        migrations.CreateModel(
            name='detalle_venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=0, max_digits=5)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ventas.libro')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ventas.venta')),
            ],
        ),
    ]
